Let's Code21:32
Fonte: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

8. Reverse a vector (first element becomes last) (★☆☆)
9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
11. Create a 3x3 identity matrix (★☆☆)
12. Create a 3x3x3 array with random values (★☆☆)
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
15. Create a 2d array with 1 on the border and 0 inside (★☆
16. How to add a border (filled with 0's) around an existing array? (★☆☆)
18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [11]:
#importanto o numpy
import numpy as np

In [1]:
#array original
arr = [1, 2, 3, 4, 5]
print("Array is :",arr)

Array is : [1, 2, 3, 4, 5]


In [4]:
#array reverso
re = arr[::-1] 
print("array reverso",re)

array reverso [5, 4, 3, 2, 1]


In [7]:
# segunda forma de fazer array reverso
re = arr
re.reverse()
print("array reverso",re)

array reverso [5, 4, 3, 2, 1]


In [10]:
#criando uma matriz 3X3 com números de 0 a 8

np.arange(0,9).reshape((3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#criando um índice de números não nulos da lista [1,2,0,0,4,0]
lst= np.array([1,2,0,0,4,0])

indnull=np.where(lst == 0)[0]
print("lista original",lst, " - indices dos numeros nulos",indnull)

lista original [1 2 0 0 4 0]  - indices dos numeros nulos [2 3 5]


In [18]:
#criando matriz identidade 3X3
ident=np.identity(3)
print ("matriz identidade 3X3")
print(ident)

matriz identidade 3X3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [19]:
#criando uma matriz 3x3x3 com valores aleatórios
mt3rand=np.random.random((3,3,3))
print ("matriz aleatória 3X3x3")
print(mt3rand)

matriz aleatória 3X3x3
[[[ 0.25826319  0.12798585  0.09119137]
  [ 0.49631602  0.68849749  0.35635929]
  [ 0.88778664  0.68258271  0.47571443]]

 [[ 0.88722115  0.90441355  0.62411413]
  [ 0.39427648  0.95154508  0.50829002]
  [ 0.42995507  0.93205406  0.098323  ]]

 [[ 0.29412867  0.38790355  0.5776375 ]
  [ 0.17233931  0.7270855   0.11522807]
  [ 0.34881919  0.82810557  0.65520308]]]


In [20]:
#matriz 10X10 com valores aleatórios 
x = np.random.random((5,5))
print("Original Array:")
print(x) 


Original Array:
[[ 0.86883773  0.53036662  0.86744972  0.19569676  0.66052362]
 [ 0.44492421  0.73004537  0.34935753  0.60174609  0.7266599 ]
 [ 0.99174276  0.87328016  0.15359187  0.78028503  0.26689279]
 [ 0.32740786  0.44550189  0.32048363  0.778507    0.99140312]
 [ 0.86754005  0.61549969  0.67874103  0.63591439  0.69039184]]


In [21]:
#mínimos e máximos da matriz
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Minimum and Maximum Values:
0.153591870242 0.991742764031


In [22]:
#matriz 2 dimensões com 1 na borda e 0 dentro

x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
1 on the border and 0 inside in the array
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [23]:
#How to add a border (filled with 0's) around an existing array?
                         
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
0 on the border and 1 inside in the array
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]


In [25]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
